<?php

use Illuminate\Database\Seeder;

class CoreUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_users')->delete();
        
        \DB::table('core_users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'first_name' => 'Rameshwor',
                'last_name' => 'Maharjan',
                'email' => 'maharjanrams+1@gmail.com',
                'username' => NULL,
                'gender' => NULL,
                'contact_number' => NULL,
                'preferences' => '',
                'password' => '$2y$10$Ih31HlWCKG6VnhhHRqOEX.kxnjA4iD2bDQyb9c60DwoQsN5jhoqoy',
                'verified' => 0,
                'email_token' => '11243aef1de80b9f59ef36f23',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-02-16 07:50:27',
                'updated_at' => '2019-02-16 07:50:27',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            1 => 
            array (
                'id' => 10,
                'first_name' => 'Rameshwor',
                'last_name' => 'Maharjan',
                'email' => 'maharjanrams@gmail.com',
                'username' => NULL,
                'gender' => NULL,
                'contact_number' => NULL,
                'preferences' => '',
                'password' => '$2y$10$lB9oJAKDc4nqFa9k9MjdmuS.bUUlSQlUbiEoVDEnm1xOOqYGHpKFK',
                'verified' => 0,
                'email_token' => '305981e34d390c5ede9a8f4a5',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-02-17 16:45:36',
                'updated_at' => '2019-02-17 16:45:36',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            2 => 
            array (
                'id' => 28,
                'first_name' => 'Sudip updated',
                'last_name' => 'Limbu updated',
                'email' => 'responsivesudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '9238298299923423',
                'preferences' => '{"subscribedCategories":[1],"savedPosts":[3,69,61,65]}',
                'password' => '$2y$10$KFHiswpZo2mSHfThVpC/d.rGHeHuZAbLtuhzH1MI08r5iO07MesPa',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => '2I4VaLSRIvhIkE7QAjwL9nVru6QTAa3qB3kvMp4NC7u2dv237WrjO3QiL8yU',
                'is_active' => 1,
                'profile_pic' => 'https://s3-ap-southeast-2.amazonaws.com/loksewa/profile/XbHUbVLRcJdnzrIoqUvlZ8H7FfGGOSYaQ2C6IGJO.jpeg',
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-02 21:30:39',
                'updated_at' => '2019-06-13 22:56:34',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            3 => 
            array (
                'id' => 29,
                'first_name' => 'Open',
                'last_name' => 'User',
                'email' => 'open_wupbohp_user@tfbnw.net',
                'username' => NULL,
                'gender' => 'female',
                'contact_number' => NULL,
                'preferences' => NULL,
                'password' => '$2y$10$WzZPFn7UeEIpb68xGbqnuOTSSXFpDXKNWhtUUE0qwAma/JiVBm976',
                'verified' => 1,
                'email_token' => 'fdcf9e24',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => 'https://s3-ap-southeast-2.amazonaws.com/loksewa/profile/2YDFyotGcdhKSmyIu0y0ScYlVDyjjl.jpeg',
                'fb_id' => 121486989032212,
                'device_id' => 'ExponentPushToken[L0xnzMDYmv-4fFNaaMXBBk]',
                'created_at' => '2019-05-03 15:14:28',
                'updated_at' => '2019-05-15 00:41:35',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            4 => 
            array (
                'id' => 30,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'testitlsdkf@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$cIzSsILts/gpg93JDHWwV.Tu.EY7Sm.yjpIKybpXUvw32QWXrCwZq',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 15:54:59',
                'updated_at' => '2019-05-04 21:52:27',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            5 => 
            array (
                'id' => 31,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesusdfsddip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$Ee2ODDSQ/SGxhLbaTeZ40OqAP1FT9ed5GuTe29aGmeZh.F0WqBg7K',
                'verified' => 1,
                'email_token' => '9e926bdb',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 21:38:55',
                'updated_at' => '2019-05-04 21:38:55',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            6 => 
            array (
                'id' => 32,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesusdfsdsddip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$pZ15nsi3S3OCjrDyET3JaOO4JxRpYZpyNIMd69YT86OoJW.K7sF/e',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 21:39:56',
                'updated_at' => '2019-05-04 21:41:12',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            7 => 
            array (
                'id' => 33,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesdsudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$MdKZ0KH27CpOLD545F85kukeEZzECLGiEPVNjpP6Fg4G27ex9PDYC',
                'verified' => 0,
                'email_token' => '37f03c09',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 21:41:53',
                'updated_at' => '2019-05-04 21:41:53',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            8 => 
            array (
                'id' => 34,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesdsdfsudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$FsClJRrIOXx4N4f1VaSrCeowbY5fJ7rKBargd0lb56gcYDBxOhveK',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 21:43:10',
                'updated_at' => '2019-05-04 21:43:32',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            9 => 
            array (
                'id' => 35,
                'first_name' => 'Sudip',
                'last_name' => 'Limbu',
                'email' => 'asfsdfasd@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '9823839283',
                'preferences' => NULL,
                'password' => '$2y$10$/WFie1Z2NxmjelTplQaZnuuizIe1l8TDH97sqxT9JiwnMV7ozr/VW',
                'verified' => 0,
                'email_token' => '269d2fc3',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-10 11:02:20',
                'updated_at' => '2019-05-10 11:02:20',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            10 => 
            array (
                'id' => 36,
                'first_name' => 'Sudip',
                'last_name' => 'Limbu',
                'email' => 'asfsdfsdfsasd@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '9823839283',
                'preferences' => NULL,
                'password' => '$2y$10$bM8adoSrqr9WN2ivhrB1b.YO2Gma0AOqXjWXmETWjZcm33OCuWcru',
                'verified' => 0,
                'email_token' => '836402c2',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => 'sddslfk23982323',
                'created_at' => '2019-05-10 11:03:06',
                'updated_at' => '2019-05-10 11:03:06',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            11 => 
            array (
                'id' => 37,
                'first_name' => 'Ava',
                'last_name' => 'Carrieroescu',
                'email' => 'hnsbqoyeyf_1555559189@tfbnw.net',
                'username' => NULL,
                'gender' => 'female',
                'contact_number' => NULL,
                'preferences' => NULL,
                'password' => '$2y$10$9xCfBR2FcXjVGkcCAlu25O/IcZ9rAabLEhLeasbluhpWs0GsQHoEO',
                'verified' => 1,
                'email_token' => '428d47ec',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => 'https://s3-ap-southeast-2.amazonaws.com/loksewa/profile/zpbuFCO5sGjPbyXSX1vc34eE0aNn96v0pcRCZdFp.jpeg',
                'fb_id' => 123288192201301,
                'device_id' => NULL,
                'created_at' => '2019-05-12 10:03:27',
                'updated_at' => '2019-05-12 10:04:30',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            12 => 
            array (
                'id' => 38,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivsdfsdesudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$wAX7oBaan34LMr3EBH3wAeIkmqVo5VqokOqJD67qLFf6dAWTuTQoK',
                'verified' => 0,
                'email_token' => 'c22315bb',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => 'sdfjs',
                'created_at' => '2019-05-13 01:44:48',
                'updated_at' => '2019-05-13 01:44:48',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            13 => 
            array (
                'id' => 39,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsisdfsdfvesudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$iTr5KyjFFIGOESC8xu2FgeeqvINmUD0WVkH1m5dTWxl1xNkEM5xPW',
                'verified' => 0,
                'email_token' => 'e711ff47',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-13 01:49:17',
                'updated_at' => '2019-05-13 01:49:17',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            14 => 
            array (
                'id' => 40,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'resposdfsdfnsivesudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$pSvsBe63uwTfUZGnX6U14e6vVEAwELCw6BiSZuQ/7V6XisFx9BKIu',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => 'ExponentPushToken[L0xnzMDYmv-4fFNaaMXBBk]',
                'created_at' => '2019-05-13 02:26:15',
                'updated_at' => '2019-05-13 02:27:14',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            15 => 
            array (
                'id' => 41,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responssdfsdfivesudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'preferences' => NULL,
                'password' => '$2y$10$X0ykQ6X6Foc5VE84kbbV6Oh5sp1aDq7Bw0TN0Afln0gGOBiK0dUDm',
                'verified' => 0,
                'email_token' => 'ef9293c8',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => 'ExponentPushToken[L0xnzMDYmv-4fFNaaMXBBk]',
                'created_at' => '2019-05-13 02:36:28',
                'updated_at' => '2019-05-13 02:36:28',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            16 => 
            array (
                'id' => 42,
                'first_name' => 'first',
                'last_name' => 'last',
                'email' => 'safslfsdj@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '23423423423',
                'preferences' => NULL,
                'password' => '$2y$10$7UgRrG0WyuCkdojKRL92QO95Qm5U3kVd86XzVvsUIZXgmjCrl14n6',
                'verified' => 0,
                'email_token' => 'a1156486',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => 'ExponentPushToken[L0xnzMDYmv-4fFNaaMXBBk]',
                'created_at' => '2019-05-14 00:39:45',
                'updated_at' => '2019-05-14 00:39:56',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
        ));
        
        
    }
}